INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (1,93,'Afghanistan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (2,358,'Aland Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (3,355,'Albania');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (4,213,'Algeria');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (5,1684,'American Samoa');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (6,376,'Andorra');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (7,244,'Angola');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (8,1264,'Anguilla');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (9,672,'Antarctica');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (10,1268,'Antigua and Barbuda');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (11,54,'Argentina');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (12,374,'Armenia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (13,297,'Aruba');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (14,61,'Australia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (15,43,'Austria');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (16,994,'Azerbaijan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (17,1242,'Bahamas');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (18,973,'Bahrain');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (19,880,'Bangladesh');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (20,1246,'Barbados');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (21,375,'Belarus');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (22,32,'Belgium');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (23,501,'Belize');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (24,229,'Benin');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (25,1441,'Bermuda');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (26,975,'Bhutan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (27,591,'Bolivia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (28,599,'Bonaire, Sint Eustatius and Saba');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (29,387,'Bosnia and Herzegovina');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (30,267,'Botswana');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (31,55,'Bouvet Island');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (32,55,'Brazil');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (33,246,'British Indian Ocean Territory');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (34,673,'Brunei Darussalam');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (35,359,'Bulgaria');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (36,226,'Burkina Faso');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (37,257,'Burundi');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (38,855,'Cambodia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (39,237,'Cameroon');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (40,1,'Canada');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (41,238,'Cape Verde');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (42,1345,'Cayman Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (43,236,'Central African Republic');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (44,235,'Chad');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (45,56,'Chile');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (46,86,'China');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (47,61,'Christmas Island');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (48,672,'Cocos (Keeling) Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (49,57,'Colombia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (50,269,'Comoros');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (51,242,'Congo');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (52,242,'Congo, Democratic Republic of the Congo');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (53,682,'Cook Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (54,506,'Costa Rica');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (55,225,'Cote D\'Ivoire');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (56,385,'Croatia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (57,53,'Cuba');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (58,599,'Curacao');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (59,357,'Cyprus');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (60,420,'Czech Republic');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (61,45,'Denmark');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (62,253,'Djibouti');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (63,1767,'Dominica');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (64,1809,'Dominican Republic');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (65,593,'Ecuador');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (66,20,'Egypt');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (67,503,'El Salvador');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (68,240,'Equatorial Guinea');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (69,291,'Eritrea');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (70,372,'Estonia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (71,251,'Ethiopia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (72,500,'Falkland Islands (Malvinas)');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (73,298,'Faroe Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (74,679,'Fiji');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (75,358,'Finland');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (76,33,'France');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (77,594,'French Guiana');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (78,689,'French Polynesia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (79,262,'French Southern Territories');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (80,241,'Gabon');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (81,220,'Gambia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (82,995,'Georgia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (83,49,'Germany');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (84,233,'Ghana');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (85,350,'Gibraltar');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (86,30,'Greece');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (87,299,'Greenland');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (88,1473,'Grenada');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (89,590,'Guadeloupe');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (90,1671,'Guam');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (91,502,'Guatemala');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (92,44,'Guernsey');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (93,224,'Guinea');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (94,245,'Guinea-Bissau');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (95,592,'Guyana');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (96,509,'Haiti');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (97,0,'Heard Island and Mcdonald Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (98,39,'Holy See (Vatican City State)');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (99,504,'Honduras');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (100,852,'Hong Kong');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (101,36,'Hungary');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (102,354,'Iceland');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (103,91,'India');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (104,62,'Indonesia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (105,98,'Iran, Islamic Republic of');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (106,964,'Iraq');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (107,353,'Ireland');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (108,44,'Isle of Man');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (109,972,'Israel');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (110,39,'Italy');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (111,1876,'Jamaica');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (112,81,'Japan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (113,44,'Jersey');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (114,962,'Jordan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (115,7,'Kazakhstan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (116,254,'Kenya');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (117,686,'Kiribati');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (118,850,'Korea, Democratic People\'s Republic of');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (119,82,'Korea, Republic of');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (120,381,'Kosovo');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (121,965,'Kuwait');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (122,996,'Kyrgyzstan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (123,856,'Lao People\'s Democratic Republic');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (124,371,'Latvia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (125,961,'Lebanon');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (126,266,'Lesotho');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (127,231,'Liberia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (128,218,'Libyan Arab Jamahiriya');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (129,423,'Liechtenstein');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (130,370,'Lithuania');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (131,352,'Luxembourg');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (132,853,'Macao');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (133,389,'Macedonia, the Former Yugoslav Republic of');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (134,261,'Madagascar');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (135,265,'Malawi');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (136,60,'Malaysia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (137,960,'Maldives');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (138,223,'Mali');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (139,356,'Malta');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (140,692,'Marshall Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (141,596,'Martinique');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (142,222,'Mauritania');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (143,230,'Mauritius');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (144,269,'Mayotte');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (145,52,'Mexico');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (146,691,'Micronesia, Federated States of');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (147,373,'Moldova, Republic of');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (148,377,'Monaco');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (149,976,'Mongolia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (150,382,'Montenegro');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (151,1664,'Montserrat');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (152,212,'Morocco');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (153,258,'Mozambique');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (154,95,'Myanmar');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (155,264,'Namibia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (156,674,'Nauru');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (157,977,'Nepal');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (158,31,'Netherlands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (159,599,'Netherlands Antilles');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (160,687,'New Caledonia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (161,64,'New Zealand');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (162,505,'Nicaragua');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (163,227,'Niger');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (164,234,'Nigeria');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (165,683,'Niue');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (166,672,'Norfolk Island');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (167,1670,'Northern Mariana Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (168,47,'Norway');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (169,968,'Oman');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (170,92,'Pakistan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (171,680,'Palau');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (172,970,'Palestinian Territory, Occupied');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (173,507,'Panama');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (174,675,'Papua New Guinea');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (175,595,'Paraguay');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (176,51,'Peru');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (177,63,'Philippines');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (178,64,'Pitcairn');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (179,48,'Poland');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (180,351,'Portugal');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (181,1787,'Puerto Rico');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (182,974,'Qatar');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (183,262,'Reunion');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (184,40,'Romania');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (185,70,'Russian Federation');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (186,250,'Rwanda');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (187,590,'Saint Barthelemy');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (188,290,'Saint Helena');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (189,1869,'Saint Kitts and Nevis');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (190,1758,'Saint Lucia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (191,590,'Saint Martin');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (192,508,'Saint Pierre and Miquelon');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (193,1784,'Saint Vincent and the Grenadines');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (194,684,'Samoa');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (195,378,'San Marino');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (196,239,'Sao Tome and Principe');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (197,966,'Saudi Arabia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (198,221,'Senegal');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (199,381,'Serbia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (200,381,'Serbia and Montenegro');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (201,248,'Seychelles');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (202,232,'Sierra Leone');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (203,65,'Singapore');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (204,1,'Sint Maarten');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (205,421,'Slovakia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (206,386,'Slovenia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (207,677,'Solomon Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (208,252,'Somalia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (209,27,'South Africa');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (210,500,'South Georgia and the South Sandwich Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (211,211,'South Sudan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (212,34,'Spain');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (213,94,'Sri Lanka');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (214,249,'Sudan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (215,597,'Suriname');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (216,47,'Svalbard and Jan Mayen');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (217,268,'Swaziland');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (218,46,'Sweden');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (219,41,'Switzerland');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (220,963,'Syrian Arab Republic');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (221,886,'Taiwan, Province of China');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (222,992,'Tajikistan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (223,255,'Tanzania, United Republic of');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (224,66,'Thailand');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (225,670,'Timor-Leste');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (226,228,'Togo');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (227,690,'Tokelau');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (228,676,'Tonga');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (229,1868,'Trinidad and Tobago');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (230,216,'Tunisia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (231,90,'Turkey');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (232,7370,'Turkmenistan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (233,1649,'Turks and Caicos Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (234,688,'Tuvalu');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (235,256,'Uganda');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (236,380,'Ukraine');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (237,971,'United Arab Emirates');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (238,44,'United Kingdom');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (239,1,'United States');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (240,1,'United States Minor Outlying Islands');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (241,598,'Uruguay');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (242,998,'Uzbekistan');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (243,678,'Vanuatu');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (244,58,'Venezuela');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (245,84,'Viet Nam');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (246,1284,'Virgin Islands, British');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (247,1340,'Virgin Islands, U.s.');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (248,681,'Wallis and Futuna');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (249,212,'Western Sahara');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (250,967,'Yemen');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (251,260,'Zambia');
INSERT IGNORE INTO `userdb`.`country` (`id`, `country_code`, `country_name`) VALUES (252,263,'Zimbabwe');