CREATE TABLE IF NOT EXISTS `user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `contact_number` bigint NOT NULL,
  `created_by_id` bigint DEFAULT NULL,
  `created_date_time` timestamp NULL DEFAULT NULL,
  `dob` date NOT NULL,
  `email_id` varchar(50) NOT NULL,
  `employee_id` varchar(20) DEFAULT NULL,
  `first_name` varchar(45) NOT NULL,
  `gender` varchar(25) NOT NULL,
  `invalid_retry_count` tinyint DEFAULT NULL,
  `is_first_time_login` bit(1) NOT NULL,
  `last_name` varchar(45) NOT NULL,
  `modified_by_id` bigint DEFAULT NULL,
  `modified_date_time` timestamp NULL DEFAULT NULL,
  `passwrd` char(128) NOT NULL,
  `passwrd_expiry_date_time` timestamp NULL DEFAULT NULL,
  `country_id` bigint DEFAULT NULL,
  `title_id` bigint DEFAULT NULL,
  `user_role_id` bigint DEFAULT NULL,
  `user_status_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_m3nrr354u2l0he9riub37ltqn` (`contact_number`),
  UNIQUE KEY `UK_r9kvst217faqa7vgeyy51oos0` (`email_id`),
  UNIQUE KEY `UK_r1usl9qoplqsbrhha5e0niqng` (`employee_id`),
  KEY `FKge8lxibk9q3wf206s600otk61` (`country_id`),
  KEY `FK4np4l2tene9mskuvawj7ku4i4` (`title_id`),
  KEY `FKh2wc2dtfdo8maylne7mgubowq` (`user_role_id`),
  KEY `FKo6g0t5ih8a5bsioca8qh5ukg3` (`user_status_id`),
  CONSTRAINT `FK4np4l2tene9mskuvawj7ku4i4` FOREIGN KEY (`title_id`) REFERENCES `title` (`id`),
  CONSTRAINT `FKge8lxibk9q3wf206s600otk61` FOREIGN KEY (`country_id`) REFERENCES `country` (`id`),
  CONSTRAINT `FKh2wc2dtfdo8maylne7mgubowq` FOREIGN KEY (`user_role_id`) REFERENCES `user_role` (`id`),
  CONSTRAINT `FKo6g0t5ih8a5bsioca8qh5ukg3` FOREIGN KEY (`user_status_id`) REFERENCES `user_status` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;